# db_constants.py

# 路径
DATABASE_PATH = './data'

# 数据库名
DATABASE_NAME = 'insight_data.db'

# 表名
TABLE_ERR_INSIGHT = 'err_insight'
TABLE_SEMESTER = 'semester'
TABLE_UNIT = 'unit'
TABLE_LESSON = 'lesson'
TABLE_QUESTION_TYPE = 'question_type'
TABLE_KNOWLEDGE_POINT = 'knowledge_point'
TABLE_ERROR_REASON = 'error_reason'

# 列名
COLUMN_ID = 'id'
COLUMN_NAME = 'name'
COLUMN_SEMESTER_ID = 'semester_id'
COLUMN_UNIT_ID = 'unit_id'
COLUMN_LESSON_ID = 'lesson_id'
COLUMN_QUESTION_TYPE_ID = 'question_type_id'
COLUMN_ERROR_REASON_ID = 'error_reason_id'
COLUMN_KNOWLEDGE_POINT_ID = 'knowledge_point_id'
COLUMN_IS_SELECTED = 'is_selected'
COLUMN_CREATED_AT = 'created_at'

# 其他常量（如果需要）
FOREIGN_KEY_SEMESTER = f'FOREIGN KEY ({COLUMN_SEMESTER_ID}) REFERENCES {TABLE_SEMESTER}({COLUMN_ID})'
FOREIGN_KEY_UNIT = f'FOREIGN KEY ({COLUMN_UNIT_ID}) REFERENCES {TABLE_UNIT}({COLUMN_ID})'
FOREIGN_KEY_LESSON = f'FOREIGN KEY ({COLUMN_LESSON_ID}) REFERENCES {TABLE_LESSON}({COLUMN_ID})'
FOREIGN_KEY_QUESTION_TYPE = f'FOREIGN KEY ({COLUMN_QUESTION_TYPE_ID}) REFERENCES {TABLE_QUESTION_TYPE}({COLUMN_ID})'
FOREIGN_KEY_ERROR_REASON = f'FOREIGN KEY ({COLUMN_ERROR_REASON_ID}) REFERENCES {TABLE_ERROR_REASON}({COLUMN_ID})'
FOREIGN_KEY_KNOWLEDGE_POINT = f'FOREIGN KEY ({COLUMN_KNOWLEDGE_POINT_ID}) REFERENCES {TABLE_KNOWLEDGE_POINT}({COLUMN_ID})'